INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ENABLED, GENDER, JOIN_DATE) VALUES ('jack', 'Jack Bauer', '1234!@#$', true, 'M', NOW());
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ENABLED, GENDER, JOIN_DATE) VALUES ('chloe', 'Chloe O Brian', '1234!@#$', true, 'F', NOW());
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ENABLED, GENDER, JOIN_DATE) VALUES ('kim', 'Kim Bauer', '1234!@#$', true, 'F', NOW());
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ENABLED, GENDER, JOIN_DATE) VALUES ('david', 'David Palmer', '1234!@#$', true, 'M', NOW());
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ENABLED, GENDER, JOIN_DATE) VALUES ('michelle', 'Michelle Dessler', '1234!@#$', true, 'M', NOW());